### ISSUE TITLE
README.md tips for white icons

### ISSUE THREAD

**Issue by typsz** [raivo-otp/issuer-icons#160]
Could we have some information about icons that are white?
Should they have specific fill color or no fill color at all?
I know that you can check other icons in the repository, but the solutions vary. Some icons are black, the others are dark gray. I don't know which option is the safest.
It would be very useful to have a tip/requirement in README.md regarding this type of icons.

Thank you

**Comment by tijme** [comment]
Hi @typsz,

Good suggestion, I will add this to the readme in the future.

To answer your question; Raivo OTP will automatically reduce the white to light gray, and black to dark gray in the app. This is to ensure that your icons are always visible in the app, no matter if dark mode is enabled or not.

In the future, I will try to make the option to upload icons for both light/dark mode.

**Comment by tijme** [comment]
Added this to the readme.
