### ISSUE TITLE
Problem with Windscribe logo

### ISSUE THREAD

**Issue by cele05** [raivo-otp/issuer-icons#271]
Hi,
first of all congratulations for your application.
I have a problem: using the dark mode I can see the icon of Windscribe while with the light theme the icon becomes all white and cannot be seen.

**Comment by tijme** [comment]
Probably fixed in https://github.com/raivo-otp/issuer-icons/commit/88f823698d382a02e53b0b856e4b359424be32fb. Can you refresh and see if it works?

**Comment by cele05** [comment]
@tijme perfect, now works perfectly...thank you so much for the availability.
