### ISSUE TITLE
./vectors/g2a.com

### ISSUE THREAD

**Issue by MhmdAMiNE** [raivo-otp/issuer-icons#287]
![g2a](https://user-images.githubusercontent.com/16267668/151785919-5a3ef614-b4d0-450b-819c-fd9be1847d94.svg)

**Comment by MhmdAMiNE** [comment]
![g2a](https://user-images.githubusercontent.com/16267668/151785614-b0fb7eeb-652b-4447-9bf8-c1badcaf36f5.svg)

**Comment by tijme** [comment]
I don't accept issues at the moment. Only pull requests.
