### ISSUE TITLE
NexusMods icon

### ISSUE THREAD

**Issue by Cimpix17** [raivo-otp/issuer-icons#96]
Hi there! 
Could the icon for [NexusMods](https://www.nexusmods.com/bootstrap/images/vortex/nmm-logomark.svg) be added? I would've done it myself but I have no clue on how to use GitHub. 
Thank you in advance.

**Comment by tijme** [comment]
HI @Cimpix17,

Unfortunately I only accept merge requests for now, as I don't have the time to add all requested icons.
